### ISSUE TITLE
On the "oho" pronounciation hint

### ISSUE THREAD

**Issue by hartwork** [peterlevi/ojo#3]
Hi!

My guess is that ojo is meant to be "eye" in Spanish but the current 'oho' for a pronunciation hint looks confusing to me. What's the idea? If ojo is Spanish, maybe [IPA](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet) notation ["[ˈoxo]"](http://de.pons.com/%C3%BCbersetzung?q=ojo&l=dees&in=&lf=de) would help more people at once, not sure. Please enlighten me what language it is.

Saludos, Sebastian

**Comment by peterlevi** [comment]
Yes, ojo is meant to be "eye" in Spanish. Also the silhouette of the word allows for a nice icon which blends it with the picture of eyes/face. 

The pronunciation I've given is using the standard (?) British pronunciation alphabet, where the "h" sound is actually written as "h", not "x". (E.g. as in the examples here: http://www.oxfordlearnersdictionaries.com/about/pronunciation_english.html). I am no expert in linguistics, today is the first time I hear the term "IPA", and using it may be more punctually correct if the word is supposed to be in Spanish, but I think the bias towards English on the internet is so large, that a lot more people would understand the correct pronunciation when they see "oho" than when they see "oxo", which would have multiple people pronouncing it "okso". I may be biased though, so everyone is welcome to give an opinion in the comments here.

**Comment by hartwork** [comment]
Good point.

**Comment by hartwork** [comment]
Good point. I checked the link though and what they use looks like IPA to me. Which use of "h" on that page do you refer to?

**Comment by peterlevi** [comment]
See all words with "h" in the section "Weak vowels /i/ and /u/", as well as "hair".
