### ISSUE TITLE
Install on debian stretch

### ISSUE THREAD

**Issue by damufo** [peterlevi/ojo#4]
How to install on debian Stretch from ppa?

**Comment by peterlevi** [comment]
As far as I know you could add PPA as repos to Debian too (http://www.webupd8.org/2014/10/how-to-add-launchpad-ppas-in-debian-via.html), but I have no experience with this.

Alternatively, you should be able to download the deb package (any of those at https://launchpad.net/~ojo/+archive/ubuntu/daily/+packages will work) and install with GDebi (https://packages.debian.org/stretch/gdebi) or a similar tool that resolves and install dependencies.

Please note I haven't tried this, and would love to hear back from someone who gives it a try. This approach does work for Variety though (https://peterlevi.com/variety/how-to-install/), which uses to a big extent the same tech stack as Ojo.

**Comment by damufo** [comment]
OK.
Install this package on Debian Stretch work for me
ojo_0.2-0~218~201902060302~ubuntu19.04.1_all.deb
Thanks.

**Comment by peterlevi** [comment]
Please note this way you get no automatically updates and there's a lot more upcoming work to happen on Ojo.

**Comment by damufo** [comment]
OK thanks!
